<?php

namespace WpSyntaxHighlighter;

class Themes {

  static public $names = [
    'default',
    'atelier-forest.light',
    'magula',
    'kimbie.light',
    'github',
    'color-brewer',
    'pojoaque',
    'atelier-forest.dark',
    'brown_paper',
    'tomorrow',
    'arta',
    'foundation',
    'tomorrow-night-blue',
    'atelier-dune.dark',
    'railscasts',
    'ir_black',
    'idea',
    'tomorrow-night-eighties',
    'atelier-dune.light',
    'docco',
    'sunburst',
    'monokai_sublime',
    'atelier-lakeside.light',
    'mono-blue',
    'solarized-light',
    'paraiso.dark',
    'codepen-embed',
    'obsidian',
    'paraiso.light',
    'vs',
    'ascetic',
    'xcode',
    'school-book',
    'rainbow',
    'dark',
    'atelier-heath.dark',
    'googlecode',
    'monokai',
    'zenburn',
    'kimbie.dark',
    'tomorrow-night',
    'solarized-dark',
    'atelier-lakeside.dark',
    'atelier-seaside.dark',
    'atelier-heath.light',
    'atelier-seaside.light',
    'far',
    'tomorrow-night-bright',
  ];

}
